"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['App.py']
DATA_FILES = ['imgs/FileReader.png']
OPTIONS = {
    'iconfile':'imgs/FileReader.png',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    py_modules=['FileErrorHandling', 'FileReader', 'Files', 'FileUtilities', 'GUI', 'Student'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
